#spring:
#  redis:
#    database: 0
#    password:
#    port: 6379
#    timeout: 100
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
debug: true